import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ba1a1a",
        tertiary: "#5600be",
        "on-primary-fixed-variant": "#0040a2",
        "on-background": "#131c2b",
        "outline-variant": "#c3c6d6",
        "surface-tint": "#0c56d0",
        "on-tertiary-fixed": "#25005a",
        "on-surface-variant": "#434654",
        "surface-container-highest": "#dae2f8",
        "on-surface": "#131c2b",
        "inverse-on-surface": "#ecf0ff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dae2f8",
        "tertiary-container": "#7029e1",
        "on-secondary-fixed-variant": "#7a3000",
        "on-secondary-container": "#572000",
        "primary-fixed": "#dae2ff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbcc",
        "inverse-surface": "#283141",
        "on-error-container": "#93000a",
        "inverse-primary": "#b2c5ff",
        secondary: "#a04100",
        outline: "#737685",
        primary: "#003d9b",
        "surface-container-low": "#f0f3ff",
        "surface-dim": "#d1daef",
        "on-primary-fixed": "#001848",
        "surface-container-high": "#e0e8fe",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#eaddff",
        "surface-bright": "#f9f9ff",
        "on-primary-container": "#c4d2ff",
        "tertiary-fixed-dim": "#d2bbff",
        "secondary-fixed-dim": "#ffb693",
        "surface-container": "#e8eeff",
        "primary-fixed-dim": "#b2c5ff",
        "primary-container": "#0052cc",
        "on-secondary-fixed": "#351000",
        "on-error": "#ffffff",
        surface: "#f9f9ff",
        "on-tertiary-container": "#decbff",
        background: "#f9f9ff",
        "secondary-container": "#fe6b00",
        "on-tertiary-fixed-variant": "#5a00c6",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
      },
      spacing: {
        "page-margin": "16px",
        gutter: "12px",
        "card-padding": "20px",
        "bottom-nav-height": "64px",
        "stack-sm": "8px",
        "top-bar-height": "56px",
        "stack-md": "16px",
      },
      fontFamily: {
        "page-title": ["var(--font-hanken)", "sans-serif"],
        "card-title": ["var(--font-hanken)", "sans-serif"],
        "body-main": ["var(--font-hanken)", "sans-serif"],
        "stat-lg": ["var(--font-hanken)", "sans-serif"],
        "technical-label": ["var(--font-jetbrains)", "monospace"],
        meta: ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "page-title": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "card-title": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-main": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "stat-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "technical-label": [
          "13px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
        meta: ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
